---
- name: Configure servers
  hosts: all
  become: true
  tasks:
    - name: Set application environment variables
      lineinfile:
        path: "/home/{{ deploy_user }}/.bashrc"
        line: "{{ item }}"
        state: present
        create: yes
      loop:
        - 'export POST_DATABASE_HOST="{{ db_host }}"'
        - 'export POST_DATABASE="posts"'
        - 'export POST_DATABASE_PORT="27017"'
        - 'export COMMENT_DATABASE_HOST="{{ db_host }}"'
        - 'export COMMENT_DATABASE_PORT="27017"'
        - 'export COMMENT_DATABASE="comments"'
      become_user: "{{ deploy_user }}"
      tags:
        - app-tag

- import_playbook: ruby.yml
- import_playbook: base.yml
- import_playbook: db.yml
- import_playbook: puma.yml
- import_playbook: deploy.yml
- import_playbook: app.yml

# Tasks for configuring the database
- name: Configure DB
  hosts: dbserver
  roles:
    - db

# Tasks for configuring the app and deploying it
- name: Configure App & Deploy
  hosts: appserver
  roles:
    - app
  vars:
    env: local
    deploy_user: ubuntu

# Show info about the env this host belongs to
- name: Show environment info
  hosts: appserver
  vars:
    env: local
  tasks:
    - debug:
        msg: "This host is in {{ env }} environment!!!"
