  # tasks file for app
  - name: Show info about the env this host belongs to
    debug:
      msg: "This host is in {{ env }} environment!!!"

  - name: Copy Flask service file to systemd
    ansible.builtin.copy:
      src: /media/groot/data/arybach_infra/ansible/roles/app/files/flask.service
      dest: /etc/systemd/system/flask.service
      owner: root
      group: root
      mode: '0644'
    become: yes

  - name: Reload systemd to recognize Flask service
    ansible.builtin.systemd:
      daemon_reload: yes
    become: yes

  - name: Enable and start Flask service
    ansible.builtin.systemd:
      name: flask
      enabled: yes
      state: started
    become: yes

  # Include Puma tasks only if it's a separate application/service
  - name: Check if Puma service is running
    command: systemctl is-active puma
    register: puma_status
    changed_when: false
    ignore_errors: true
    check_mode: false
    become: yes

  - name: Start Puma service if it's stopped
    command: systemctl start puma
    when: puma_status.stdout != "active"
    become: yes
