---
# handlers file for app
- name: reload puma
  systemd:
    name: puma
    state: restarted
    daemon_reload: yes
  become: yes

- name: restart puma
  systemd:
    name: puma
    state: restarted
  become: yes

- name: reload systemd
  ansible.builtin.command:
    cmd: systemctl daemon-reload
  become: yes
